server:
  port: 11280
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json

mybatis-plus:
  configuration:
    # 关闭二级缓存
    cache-enabled: false
    # 设置本地缓存作用域
    local-cache-scope: SESSION

spring:
  freemarker:
    check-template-location: false
  profiles:
    # 激活的环境，如果需要 quartz 分布式支持，需要修改 active: dev,quartz
    active: dev
  main:
    allow-circular-references: true
  data:
    redis:
      repositories:
        enabled: false
#  pid:
#    file: /自行指定位置/eladmin.pid

task:
  pool:
    # 核心线程池大小
    core-pool-size: 10
    # 最大线程数
    max-pool-size: 30
    # 活跃时间
    keep-alive-seconds: 60
    # 队列容量
    queue-capacity: 50

#七牛云
qiniu:
  # 文件大小 /M
  max-size: 15

#邮箱验证码有效时间/秒
code:
  expiration: 300

#密码加密传输，前端公钥加密，后端私钥解密
rsa:
  private_key: MIIBUwIBADANBgkqhkiG9w0BAQEFAASCAT0wggE5AgEAAkEA0vfvyTdGJkdbHkB8mp0f3FE0GYP3AYPaJF7jUd1M0XxFSE2ceK3k2kw20YvQ09NJKk+OMjWQl9WitG9pB6tSCQIDAQABAkA2SimBrWC2/wvauBuYqjCFwLvYiRYqZKThUS3MZlebXJiLB+Ue/gUifAAKIg1avttUZsHBHrop4qfJCwAI0+YRAiEA+W3NK/RaXtnRqmoUUkb59zsZUBLpvZgQPfj1MhyHDz0CIQDYhsAhPJ3mgS64NbUZmGWuuNKp5coY2GIj/zYDMJp6vQIgUueLFXv/eZ1ekgz2Oi67MNCk5jeTF2BurZqNLR3MSmUCIFT3Q6uHMtsB9Eha4u7hS31tj1UWE+D+ADzp59MGnoftAiBeHT7gDMuqeJHPL4b+kC+gzV4FGTfhR9q3tTbklZkD2A==

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}

data:
  # 数据加密，数据库公钥加密，业务中私钥解密
  rsa:
    public_key: ENC(85fbGYk8ZeGf9AE4aBdnht6/XRNok4DvBJAViPRJI7xHQ+sR8AKMprC03Fzs6Kn1fW3B9OeHB0wMfcpYixnDf9Vpqn6apMn3xIbkPFTKFF4Y3FQ+o9P4hCy8ifNpOXIorTT5lGphSa0T/NAtko8OHWiKXessYx37g9fqwjP+eMEzyNT05Fy3cB1GnmLR2kbzSz41xnnANq2dJC0cWd9ZbMQzPVM7NS+oeMXRvq40Kmu3mM3/D7r8FseLKnGCRB+rZlFxyBVtVTeFT2J8X8Y3DsgX7XoJ1f72+AFMXWl7qoO0QZ8sOyXUEghOxZchlrhT/ZrdG2602nxTApiPP8t8cw==)
    private_key: ENC(/AcTbM1UqO7VZP0wUmXpsuGvH82leqAGlDDlvRwS7Qb7YvZV8qyIFrFcZD2uZCQDNex5l03ZyZDroy7ZYRlGUPV69idszEhHwgZHRIHE+F04DAC8fG7FAtmVy1j2D1Xmnd+PSqEUMRNEodRO/wPNdnQPbzAZtTEZ9cCyLAiXjEL/pjDBII9Np5jDoV7UX/xykaDX8IOj/l2xbqINH0iSSccnj42Q8ilfBr0YGY4GEHhyfMoHDqaBtbK9Oox7YR+1JCIAxOim+DqM13k9njA9g0FPTWnQEKZE0Ly0fp6ZMNZcnDB1NTXmMtdinG/M4X/YxHkTJNn897W/B8c6JJXeRsM/Xp0Ev/gUYjJ/iuc6Ndyf3A7xhkPggqwHsVzSLXTAocdAKH4a10BDsNpboDZaqgql8x42MZTM/XEYTCdwYYZ2sVahL2TfYzYsoxr/FKIplenik662KQ6939Bz1wD3s5rxlqDZ52/gnzNmOkjt0QVFw8Z7S0KNlz9NkYUmtTyswuCeDDXHex9jx9/oFpumEzV09pDBJUIWEobjz0Mx0tBUUt70+aDbqeVIh/ooW9udVPOlCkG71N1hmiyqsApeVagLag7X/UBZ0tZTbkpJhTti1/v1R9b2x3LlAq+ftb9YIMa0B7iju2654/YaWTpd9SQIe0lyKvbYO1YfAQfanlZPqnqXjEWc0OzYRbE2AD+P4P6xsVu5ys0LcbMjmWoq0/x3sBWcz6HCYcpguK9PijIDgVUSkbgEYGhH57+UVI7tTlbJoH8aU98hlPDH5kB6KVt38w6CPY8SgZ8uKVyY/DgMbHbuoOgmh0I983Sle+U1j7v73VLqtGWhEYlBbGByNKneJJF9xHmvi/CwJc1PNBBueIXoJ3UMFhY+w4J9L2a/5lTh6v2+fpUXjdPsoXJIAHoCaexQ982jvPQDzbLfdo/MT15IfcDX4GLSDXRkCoylkai9Zlier+u4CqRE1RoylS3WTxnvsKdn4qWtMvrq9XG81x5067xZAq68uDT6P0C59j7z3mapGWZ7vu5x+fm9l88Wpy2k4KCGR+GdRAdJQgGFSVKxvkaZcFR5gRSXg4xiGsuokp9NuDJ4SoInRyWBvWHq+Om1iEMEuO7WYaGYxMG/Htq3GXYXxbraGkBUH5yk1p5Lli/jOGK2peu4FHpUlfB9v9SLzoAA/w1h2aM8pdY=)

# 币安密钥
binance:
  spot:
    api_host: https://api.binance.com
  usd_futures:
    api_host: https://fapi.binance.com
  coin_futures:
    api_host: https://dapi.binance.com

tradingview:
  notify:
    secret: ENC(ewlbFjZaqaSlt4R5B62redFCkI2g7cwnFSHGlXdMqqawghNLbH1HUgzosZBFr+yaVZ32rhpaqL5NDAlVcSjWASafAdD/TAVn5EPIL6EvZqg=)

aliyun:
  ocr:
    accessKey:
      id: ENC(n2qNt7+yiCf910GWL1ksqVV9kyqzlOmdnTdN4D8i6U+riRPfkirmqZQby0XkjxCl9977nUTdFUgICZmM0tkf8Q==)
      secret: ENC(elanvxCCUcwvk/jm6ftD/DstlukjzneYkLgxMfWzyoofhRiJ/AqXvFGG8tOu7Q4SCH8SyBERanrj0c4t0VqQaw==)
    endpoint: ocr-api.cn-hangzhou.aliyuncs.com
  dingding:
    notify:
      webhook: ENC(dttWSAgpAR4TYtxeWtnj4bSfGN2RhcrAFEeRjjrVWWTDFBXHIoPSEWoPFpq/Db3Uimz5zgiWfqTtcKD2gyijXQSovOxqIeGBEDKAGShQSV6YB2fDL3AnR71zV6HYr0nMSpPcQv5AKUNzp10CWrlCvz+M3HoK/Mz87uevLRKrHbM/w6Ed/2iiHWnVs81wo9dEVXNmq1btwN40EN1ySRaEQw==)
      secret: ENC(ekuTOF9Cv/8B+B72Oayj1Lyx/4IiWX6xMPBkEjD6ijhHmFXMQQjOF++tnX6MXwNrkaN0LwNRme1Y1+XE30Ytt0GkXdHGlzLz7WloNYCYI76372NqAsfFJfcVbj7k2YIWos0ylQ+KDsd0Y9snuPvJZw==)
